spring.application.name=EcopointsP2
spring.security.user.name=user
spring.security.user.password=ecolink
spring.profiles.active=dev
spring.data.mongodb.uri=mongodb://localhost:27017/ecopoints
spring.data.mongodb.auto-index-creation=true
server.port=8080

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=110MB
jwt.secret=ecolink-hemmelig-noegle-mindst-32-tegn-lang 
